mae:
  _target_: "tsl.metrics.torch.MaskedMAE"
mape:
  _target_: "tsl.metrics.torch.MaskedMAPE"
mre:
  _target_: "tsl.metrics.torch.MaskedMRE"
mae@0:
  _target_: "tsl.metrics.torch.MaskedMAE"
  at: 0
mae@25:
  _target_: "tsl.metrics.torch.MaskedMAE"
  at: "${math: '${data.torch_dataset.horizon} // 4 - 1'}"
mae@50:
  _target_: "tsl.metrics.torch.MaskedMAE"
  at: "${math: '${data.torch_dataset.horizon} // 2 - 1'}"
mae@100:
  _target_: "tsl.metrics.torch.MaskedMAE"
  at: "${math: '${data.torch_dataset.horizon} - 1'}"
mmre:
  _target_: "src.metrics.MultivariateMaskedMRE"
  dim: 1
